2022-01-27 06:48:58,223 INFO    MainThread:452 [internal.py:wandb_internal():91] W&B internal server running at pid: 452, started at: 2022-01-27 06:48:58.223256
2022-01-27 06:48:58,224 DEBUG   HandlerThread:452 [handler.py:handle_request():120] handle_request: check_version
2022-01-27 06:48:58,224 INFO    WriterThread:452 [datastore.py:open_for_write():77] open: /workspace/graph-neural-pde/src/wandb/run-20220127_064857-grandpp-alpha=1.0-T=0.1/run-grandpp-alpha=1.0-T=0.1.wandb
2022-01-27 06:48:58,226 DEBUG   SenderThread:452 [sender.py:send():160] send: header
2022-01-27 06:48:58,226 DEBUG   SenderThread:452 [sender.py:send():160] send: request
2022-01-27 06:48:58,226 DEBUG   SenderThread:452 [sender.py:send_request():169] send_request: check_version
2022-01-27 06:48:58,470 DEBUG   SenderThread:452 [sender.py:send():160] send: run
2022-01-27 06:48:58,966 ERROR   SenderThread:452 [internal_api.py:execute():127] 409 response executing GraphQL.
2022-01-27 06:48:58,968 ERROR   SenderThread:452 [internal_api.py:execute():128] {"errors":[{"message":"Error 1062: Duplicate entry '644113-grandpp-alpha=1.0-T=0.1' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-01-27 06:49:00,541 ERROR   SenderThread:452 [internal_api.py:execute():127] 409 response executing GraphQL.
2022-01-27 06:49:00,542 ERROR   SenderThread:452 [internal_api.py:execute():128] {"errors":[{"message":"Error 1062: Duplicate entry '644113-grandpp-alpha=1.0-T=0.1' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-01-27 06:49:03,223 ERROR   SenderThread:452 [internal_api.py:execute():127] 409 response executing GraphQL.
2022-01-27 06:49:03,224 ERROR   SenderThread:452 [internal_api.py:execute():128] {"errors":[{"message":"Error 1062: Duplicate entry '644113-grandpp-alpha=1.0-T=0.1' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-01-27 06:49:03,225 ERROR   SenderThread:452 [retry.py:__call__():111] Retry attempt failed:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/wandb/old/retry.py", line 96, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    six.reraise(*sys.exc_info())
  File "/opt/conda/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 124, in execute
    return self.client.execute(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/opt/conda/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2022-01-27 06:49:07,686 ERROR   SenderThread:452 [internal_api.py:execute():127] 409 response executing GraphQL.
2022-01-27 06:49:07,687 ERROR   SenderThread:452 [internal_api.py:execute():128] {"errors":[{"message":"Error 1062: Duplicate entry '644113-grandpp-alpha=1.0-T=0.1' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-01-27 06:49:07,868 WARNING MainThread:452 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-27 06:49:09,293 WARNING MainThread:452 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-01-27 06:49:09,293 ERROR   MainThread:452 [internal.py:wandb_internal():149] Internal process interrupted.
2022-01-27 06:49:09,478 INFO    WriterThread:452 [datastore.py:close():258] close: /workspace/graph-neural-pde/src/wandb/run-20220127_064857-grandpp-alpha=1.0-T=0.1/run-grandpp-alpha=1.0-T=0.1.wandb
2022-01-27 06:49:09,483 INFO    HandlerThread:452 [handler.py:finish():624] shutting down handler
